# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/in.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module IN # :nodoc:
    def self.defined_regions
      [:in]
    end

    def self.holidays_by_month
      {
                1 => [{:mday => 1, :observed => "to_weekday_if_weekend(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:in]},
            {:mday => 14, :name => "Makara Sankranti", :regions => [:in]},
            {:mday => 26, :name => "Republic Day", :regions => [:in]}],
      3 => [{:mday => 1, :name => "Maha Shivaratri", :regions => [:in]},
            {:mday => 18, :name => "Holi", :regions => [:in]},
            {:mday => 22, :name => "Rang Panchami", :regions => [:in]}],
      4 => [{:mday => 15, :name => "Good Friday", :regions => [:in]}],
      5 => [{:mday => 3, :name => "Idul Fitr", :regions => [:in]}],
      8 => [{:mday => 18, :name => "Janmashtami", :regions => [:in]},
            {:mday => 31, :name => "Ganesh Chaturthi", :regions => [:in]}],
      10 => [{:mday => 5, :name => "Vijaya Dashami / Dussehra", :regions => [:in]},
            {:mday => 24, :name => "Diwali", :regions => [:in]},
            {:mday => 25, :name => "Diwali", :regions => [:in]}],
      11 => [{:mday => 1, :name => "Kannada Rajyotsava", :regions => [:in]}]
      }
    end

    def self.custom_methods
      {
          
      }
    end
  end
end
